export const PAGE_SIZE = 15

export const DICTIONARY = {
  ru: {
    title: 'Аналитика цен',
    loading: 'Сбор рыночных данных…',
    error: 'Не удалось загрузить данные',
    retry: 'Повторить попытку',
    search: 'Поиск по артикулу или названию...',
    allSources: 'Все источники',
    favorites: 'Отслеживаемые',
    sortDefault: 'Популярные',
    sortUnitPriceAsc: 'Минимальная цена (за 1 ед.)',
    sortSavings: 'Максимальный спред',
    sortName: 'Алфавитный порядок',
    code: 'Арт.',
    bestPrice: 'Лучшее предложение',
    saveUpTo: 'Спред',
    statsTotal: 'индексов',
    statsAvgSpread: 'Ср. волатильность',
    empty: 'Рыночных данных не найдено',
    emptyHint: 'Смягчите критерии поиска для отображения результатов',
    noPrice: 'Нет в наличии',
    singleOffer: 'Монопольное предложение',
    loadMore: 'Загрузить следующие',
    updatedAt: 'Обновлено',
    priceLag: 'Задержка котировки',
    deficit: 'Риск дефицита',
    priceRise: 'Ожидается рост цены',
    urgentBuy: 'Рекомендация к покупке',
    priceHistory: 'История цен',
    historyOldest: 'Старые',
    historyNewest: 'Новые',
    historyPoints: 'замеров',
    historySingleTitle: 'История ещё копится',
    historySingleHint:
      'В базе пока мало замеров по этой позиции. График появится после следующих обновлений парсера.',
    volatilityTitle: 'Средняя волатильность',
    spreadTitle: 'Разрыв цен (Spread)',
    gotIt: 'Понятно',
    recommendationLabel: 'Стратегия',
    spreadLow:
      'Цены на рынке почти идентичны. Выгоднее выбирать поставщика с наиболее удобной логистикой или лучшим сервисом, так как разница в цене минимальна.',
    spreadMid:
      'Заметная разница в цене. Это хорошая возможность сэкономить, выбрав более выгодное предложение, если сроки доставки вас устраивают.',
    spreadHigh:
      'На рынке сильный ценовой перекос по данной позиции. Настоятельно рекомендуем закупать объем у выделенного цветом поставщика, чтобы максимизировать вашу маржинальность.',
    volLow:
      'Рынок в данной категории абсолютно стабилен, цены у поставщиков держатся на одном уровне. Срочности в оптимизации закупок нет.',
    volMid:
      'Наблюдаются умеренные колебания цен. Оптимальное время для точечной экономии на конкретных позициях из списка.',
    volHigh:
      'Рынок крайне нестабилен. Это лучшее время для оптимизации — тщательно сравнивайте цены, так как разница у поставщиков сейчас огромна.',
  },
  uk: {
    title: 'Аналітика цін',
    loading: 'Збір ринкових даних…',
    error: 'Не вдалося завантажити дані',
    retry: 'Повторити спробу',
    search: 'Пошук за артикулом або назвою...',
    allSources: 'Всі джерела',
    favorites: 'Відстежувані',
    sortDefault: 'Популярні',
    sortUnitPriceAsc: 'Мінімальна ціна (за 1 од.)',
    sortSavings: 'Максимальний спред',
    sortName: 'Алфавітний порядок',
    code: 'Арт.',
    bestPrice: 'Найкраща пропозиція',
    saveUpTo: 'Спред',
    statsTotal: 'індексів',
    statsAvgSpread: 'Сер. волатильність',
    empty: 'Ринкових даних не знайдено',
    emptyHint: 'Помʼякшіть критерії пошуку для відображення результатів',
    noPrice: 'Немає в наявності',
    singleOffer: 'Монопольна пропозиція',
    loadMore: 'Завантажити наступні',
    updatedAt: 'Оновлено',
    priceLag: 'Затримка котирування',
    deficit: 'Ризик дефіциту',
    priceRise: 'Очікується зростання ціни',
    urgentBuy: 'Рекомендація до покупки',
    priceHistory: 'Історія цін',
    historyOldest: 'Старі',
    historyNewest: 'Нові',
    historyPoints: 'замірів',
    historySingleTitle: 'Історія ще накопичується',
    historySingleHint:
      'У базі поки мало замірів по цій позиції. Графік зʼявиться після наступних оновлень парсера.',
    volatilityTitle: 'Середня волатильність',
    spreadTitle: 'Розрив цін (Spread)',
    gotIt: 'Зрозуміло',
    recommendationLabel: 'Стратегія',
    spreadLow:
      'Ціни на ринку майже ідентичні. Вигідніше обирати постачальника з найбільш зручною логістикою.',
    spreadMid:
      'Помітна різниця в ціні. Це гарна можливість заощадити, обравши вигіднішу пропозицію.',
    spreadHigh:
      'На ринку сильний ціновий перекіс. Настійно рекомендуємо закуповувати обсяг у виділеного кольором постачальника для максимізації маржинальності.',
    volLow: 'Ринок стабільний, ціни у постачальників тримаються на одному рівні.',
    volMid: 'Помірні коливання цін. Оптимальний час для точкової економії.',
    volHigh:
      'Ринок украй нестабільний. Це найкращий час для оптимізації закупівель — ретельно порівнюйте ціни.',
  },
  de: {
    title: 'Preisanalyse',
    loading: 'Marktdaten werden erfasst…',
    error: 'Daten konnten nicht geladen werden',
    retry: 'Erneut versuchen',
    search: 'Suche nach Artikelnummer oder Name...',
    allSources: 'Alle Quellen',
    favorites: 'Beobachtet',
    sortDefault: 'Beliebt',
    sortUnitPriceAsc: 'Günstigste (pro Einheit)',
    sortSavings: 'Max. Spread',
    sortName: 'Alphabetisch',
    code: 'Art.',
    bestPrice: 'Bestes Angebot',
    saveUpTo: 'Spread',
    statsTotal: 'Indizes',
    statsAvgSpread: 'Ø Volatilität',
    empty: 'Keine Marktdaten gefunden',
    emptyHint: 'Lockern Sie die Suchkriterien, um Ergebnisse zu sehen',
    noPrice: 'Nicht auf Lager',
    singleOffer: 'Monopolangebot',
    loadMore: 'Weitere laden',
    updatedAt: 'Aktualisiert',
    priceLag: 'Preisverzögerung',
    deficit: 'Engpassrisiko',
    priceRise: 'Preisanstieg erwartet',
    urgentBuy: 'Kaufempfehlung',
    priceHistory: 'Preisverlauf',
    historyOldest: 'Älter',
    historyNewest: 'Neuer',
    historyPoints: 'Messungen',
    historySingleTitle: 'Verlauf wird noch aufgebaut',
    historySingleHint:
      'Noch zu wenige Messpunkte. Der Chart erscheint nach den nächsten Parser-Updates.',
    volatilityTitle: 'Ø Volatilität',
    spreadTitle: 'Spread (Preisdifferenz)',
    gotIt: 'Verstanden',
    recommendationLabel: 'Strategie',
    spreadLow:
      'Die Preise sind nahezu identisch. Wählen Sie den Lieferanten mit der bequemsten Logistik.',
    spreadMid:
      'Spürbarer Preisunterschied. Eine gute Gelegenheit, durch die günstigere Option Geld zu sparen.',
    spreadHigh:
      'Starkes Preisungleichgewicht. Wir empfehlen dringend, beim farblich markierten Lieferanten zu kaufen.',
    volLow: 'Der Markt ist stabil, die Preise bleiben auf einem Niveau.',
    volMid: 'Moderate Preisschwankungen. Optimale Zeit für gezielte Einsparungen.',
    volHigh:
      'Der Markt ist instabil. Die beste Zeit zur Einkaufsoptimierung – vergleichen Sie die Preise.',
  },
}

export const BRAND_ALIASES: Array<[RegExp, string]> = [
  [/найр[іи]т/gi, 'nairit'],
  [/десмокол/gi, 'desmokol'],
  [/dismakol/gi, 'desmokol'],
  [/бон[іи]кол/gi, 'bonikol'],
  [/затверджувач/gi, 'hardener'],
  [/отвердитель/gi, 'hardener'],
  [/мультиф[іи]кс/gi, 'sarmultifix'],
  [/протрава/gi, 'preparatore'],
  [/протравка/gi, 'preparatore'],
  [/протирання/gi, 'preparatore'],
  [/слоник/gi, 'solution'],
  [/(г|ґ)умов(ий|ої|а|е|і)/gi, 'rubber'],
  [/резинов(ый|ой|ая|ое|ые)/gi, 'rubber'],
  [/поліуретанов(ий|ої|а|е|і)/gi, 'polyurethane'],
  [/полиуретанов(ый|ой|ая|ое|ые)/gi, 'polyurethane'],
  [/поліхлоропренов(ий|ої|а|е|і)/gi, 'polychloroprene'],
  [/полихлоропренов(ый|ой|ая|ое|ые)/gi, 'polychloroprene'],
]
