name: Build & E2E Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
        
      # Устанавливаем движки браузеров для Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        
      # Запускаем наш E2E-тест
      - name: Run Playwright Tests
        run: npm run test:e2e
