name: Code Quality & Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # Кэш отключен, так как нет package-lock.json

      - name: Install dependencies
        # Используем обычный install, он сам сгенерирует нужные связи
        run: npm install

      - name: Check types and Build project
        # Эта команда запустит "tsc -b && vite build" из твоего package.json
        run: npm run build
