name: scrape-macro

on:
  workflow_dispatch: # Кнопка для ручного запуска в любое время
  schedule:
    - cron: '0 3 * * 0' # Автоматический запуск каждое воскресенье в 3 часа ночи

jobs:
  scrape-macro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run macro scraper
        run: node src/pages/PricesPage/scripts/macro-sync.mjs
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
