name: Обновление картинок StockX

on:
  workflow_dispatch: 

jobs:
  run-puppeteer-script:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Устанавливаем нужные библиотеки
        run: npm install pg puppeteer puppeteer-extra puppeteer-extra-plugin-stealth axios form-data

      - name: Запускаем скрипт-парсер
        env:
          NEON_DATABASE_URL: ${{ secrets.DATABASE_URL }} 
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
        run: node scripts/update-images.js
